### ISSUE TITLE
About experiment result

### ISSUE THREAD

**Issue by lhxandcxy** [felipecruz/CFRBM#2]
Hi @felipecruz, what is you rmse  in your experiment using movielens dataset?

**Comment by felipecruz** [comment]
Hello @lhxandcxy . What dataset are you referring? ml-100k?

I achieved the same results (MAE) as this work: http://people.ischool.berkeley.edu/~nakov/selected_papers_list/ICML2013_CF_Botzmann_poster.pdf

**Comment by lhxandcxy** [comment]
Hello@ @felipecruz .Thanks! I will try to run your code later :)

**Comment by lhxandcxy** [comment]
Hello @felipecruz. I have rewritten your code without theano and run successfully! Thanks a lot!
I also achieved the same MAE as the work you mentioned. 

However , I wonder why I didn't achieved the rmse as the work in "Restricted Boltzmann machines for collaborative filtering", I achieved almost 1.05 and it achieved 0.95 or less when k=1 in the paper.

I read the paper before, it uses softmax unit as RBM visible unit. It makes no difference to expand softmax unit in your code, but I am quiet confused about sampling visible units. As a softmax unit, it can be sampled by multinomial distribution. In your code, you sample the visible units using binomial distribution. Look forward to your reply :)  .

**Comment by ngcthuong** [comment]
I also rewrite it in Matlab and also got 1.05 RMSE error. Still not figure out why.

**Comment by felipecruz** [comment]
Hello @lhxandcxy . Your point is valid. The binomial was kind of inherited from the regular RBM model where each unit is handled individually. Here's an attempt to change that portion of the code to sample from multinomial.

https://github.com/felipecruz/CFRBM/compare/feature/sample_visible_from_multinomial?expand=1

Can you check? thanks in advance both of you

**Comment by lhxandcxy** [comment]
Hello @felipecruz . It seems that sampling visible units from multinomial makes little difference. It also gets 1.06 rmse and converges more slowly. Besides, I tried the same parameters like "Restricted Boltzmann machines for collaborative filtering", and didn't solve the problem still.

**Comment by felipecruz** [comment]
Hello @lhxandcxy .Thanks on your feedback. If I come up with an new idea I'll let you know. If you have another idea let me know also. Thanks
